language: ruby
services:
  - mysql
rvm:
  - "2.5.0"
  - "2.4.0"
env:
  - DB=mysql
install:
  - bundle install --path vendor/
before_script:
  - cp config/database.yml.travis config/database.yml
script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rails test
